import os
import sys

APP_DIR = os.path.dirname(
    os.path.abspath(sys.executable if getattr(sys, "frozen", False) else __file__)
)
RESOURCE_DIR = (
    getattr(sys, "_MEIPASS", APP_DIR)
    if getattr(sys, "frozen", False)
    else APP_DIR
)
MODEL_DIR = (
    os.path.join(RESOURCE_DIR, "models")
    if getattr(sys, "frozen", False)
    else APP_DIR
)
BASE_DIR = APP_DIR
WINDOW_NAME = "AI Driver Drowsiness Detector"
DEBUG_MODE = False
CAMERA_INDEX = 0

MODEL_YUNET = os.path.join(MODEL_DIR, "face_detection_yunet_2023mar.onnx")
MODEL_DLIB = os.path.join(MODEL_DIR, "shape_predictor_68_face_landmarks.dat")
LOG_DIR = os.path.join(APP_DIR, "logs")
APPLICATION_LOG_PATH = os.path.join(LOG_DIR, "application.log")
SESSION_LOG_DIR = os.path.join(APP_DIR, "session_logs")

FACE_CONFIDENCE_THRESHOLD = 0.35
FACE_NMS_THRESHOLD = 0.30
FACE_TOP_K = 5000
FACE_DETECTION_INTERVAL = 0.10
FACE_LOST_GRACE_TIME = 0.75

CALIBRATION_TIME = 2.0
CALIBRATION_MIN_SAMPLES = 25
CALIBRATION_OPEN_RATIO = 0.75

EYE_OPEN_THRESHOLD = 0.22
EYE_CLOSED_THRESHOLD = 0.12
EYE_CLOSURE_CONFIRM_TIME = 0.65
EYE_REOPEN_THRESHOLD = 0.16
BLINK_MIN_DURATION = 0.08
BLINK_MAX_DURATION = 0.65
BLINK_CANDIDATE_BASELINE_RATIO = 0.90
BLINK_EVIDENCE_BASELINE_RATIO = 0.82
BLINK_REFRACTORY_PERIOD = 0.20
EYE_OPEN_BASELINE_RATIO = 0.80
EYE_CLOSED_BASELINE_RATIO = 0.55
EYE_UNCERTAIN_GRACE_TIME = 0.20
EYE_PERCLOS_WINDOW_SECONDS = 20.0
EYE_VALID_GAP_SECONDS = 0.50
EYE_CLOSURE_WARNING_TIME = 3.0
EYE_CLOSURE_SCORE_MAX = 80.0
PERCLOS_SCORE_MAX = 25.0
PERCLOS_SCORE_THRESHOLD = 0.35
PERCLOS_MIN_HISTORY_SECONDS = 3.0
RECOVERY_RATE_PER_SECOND = 14.0
SCORE_RISE_RATE_PER_SECOND = 35.0
ALARM_OFF_SCORE = 60

YAWN_THRESHOLD = 0.30
YAWN_CONFIRM_TIME = 1.8
YAWN_RELEASE_RATIO = 0.72
YAWN_COOLDOWN = 2.0
YAWN_RECOVERY_CONFIRM_TIME = 0.35
YAWN_REARM_TIME = 0.50
MOUTH_CALIBRATION_MIN_SAMPLES = 25
MOUTH_CALIBRATION_MAX_RATIO = 0.36
MOUTH_YAWN_BASELINE_FACTOR = 1.50
MOUTH_YAWN_BASELINE_MARGIN = 0.12
MOUTH_OPEN_HYSTERESIS_RATIO = 0.85
YAWN_SCORE_MAX = 10.0
YAWN_SCORE_DECAY_SECONDS = 30.0

HEAD_DOWN_THRESHOLD = 16.0
HEAD_DOWN_CONFIRM_TIME = 1.2
HEAD_TILT_SMOOTHING = 0.25
HEAD_DOWN_GRACE_TIME = 0.25
HEAD_POSE_SCORE_MAX = 15.0
HEAD_DOWN_FULL_SCORE_SECONDS = 2.0

BLINK_HISTORY_SECONDS = 60.0
BLINK_ABNORMAL_COUNT_PER_MINUTE = 25
BLINK_PATTERN_SCORE_STEP = 0.5
BLINK_PATTERN_SCORE_MAX = 8.0

FACE_LOSS_RESET_TIME = 0.75
MIN_FACE_WIDTH = 80
MIN_FACE_HEIGHT = 80
LANDMARK_FACE_MARGIN_RATIO = 0.25
MIN_EYE_WIDTH = 5.0
MIN_MOUTH_WIDTH = 8.0

ALARM_SCORE = 75
ALARM_REPEAT_SECONDS = 0.55

MIN_DROWSINESS_SCORE = 0
MAX_DROWSINESS_SCORE = 100

STATUS_BANDS = {
    "NORMAL": (0, 24),
    "CAUTION": (25, 49),
    "RISK": (50, 74),
    "WARNING": (75, 100),
}

PREFERRED_FACE_LABELS = {
    "PROBABLE_DRIVER": "PROBABLE DRIVER",
    "OTHER_FACE": "OTHER FACE",
    "NOT_DETECTED": "FACE NOT DETECTED",
}
